### ISSUE TITLE
Channels created without a specified GUID do not use the default page

### ISSUE THREAD

**Issue by rtzoeller** [NIVeriStandAdd-Ons/VeriStand-Addon-System-Definition-Utilities#5]
`CreateChannel.vi` does not have the default GUID value for the wrapped VI passed through, which causes issues if the GUID is not explicitly specified.
![image](https://user-images.githubusercontent.com/573497/47661516-34dfd980-db67-11e8-9f62-16bce3834aec.png)

**Comment by czokubik** [comment]
There is no default GUID for both create channel and create section. I'll fix that in my next commit.

**Comment by czokubik** [comment]
That was an easy fix. I also created a new build.
