### ISSUE TITLE
TreeItem Properties Get (Set ) loses the information that the string is/is not binary

### ISSUE THREAD

**Issue by czokubik** [NIVeriStandAdd-Ons/VeriStand-Addon-System-Definition-Utilities#6]
Flag "binary string" is lost when using TreeItem.Property.Get.vi. Data integrity of the binary sting can be corrupted a consequence of calling "TreeItem.Property.Set.vi" without the "binary string" = true flag. Solution is to write/read specific variant attribute to both functions to store this additional info within the variant.

**Comment by keprt** [comment]
Fixed by merge
